### ISSUE TITLE
Cannot publish config on L5

### ISSUE THREAD

**Issue by BradleyDeLar** [twosuperior/registry#2]
`php artisan config:publish "twosuperior\registry"` doesn't work in Laravel 5

```
C:\xampp\htdocs\xxx.test>php artisan config:publish "twosuperior\registry"



  [InvalidArgumentException]
  Command "config:publish" is not defined.
  Did you mean one of these?
      vendor:publish
      config:clear
      config:cache




C:\xampp\htdocs\xxx.test>php artisan vendor:publish "twosuperior\registry"



  [RuntimeException]
  Too many arguments.




C:\xampp\htdocs\xxx.test>php artisan vendor:publish
Can't locate path: <C:\xampp\htdocs\xxx.test\vendor\twosuperior\registry\src\Two
superior/config/config.php>
Can't locate path: <C:\xampp\htdocs\xxx.test\vendor\twosuperior\registry\src\Two
superior/migrations/>
Publishing Complete!
```

**Comment by ghost** [comment]
http://laravel.io/forum/01-16-2015-laravel-5-package-configuration - I had the same issue with authority  in the end i just copied it in manually and that seemed to work!

**Comment by BradleyDeLar** [comment]
I've just had a look and I believe it's just a case of correcting the paths on https://github.com/twosuperior/registry/blob/master/src/Twosuperior/Registry/RegistryServiceProvider.php#L23

**Comment by kashaigili** [comment]
use "php artisan vendor:publish"

**Comment by richarddavey** [comment]
We've updated the publish method and also the readme e2449f1b0b539fc38b0c7ea85877670a1c62dfd0
